const pool = require('./database');

const createCloudTables = async (connection) => {
    await connection.query(`
        CREATE TABLE IF NOT EXISTS client_devices (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            device_uuid VARCHAR(64) UNIQUE NOT NULL,
            name VARCHAR(100),
            platform VARCHAR(20) NOT NULL,
            app_version VARCHAR(20),
            refresh_token_hash CHAR(64),
            refresh_expires_at TIMESTAMPTZ,
            prev_refresh_token_hash CHAR(64),
            prev_refresh_valid_until TIMESTAMPTZ,
            token_generation INTEGER NOT NULL DEFAULT 1,
            last_seen_at TIMESTAMPTZ,
            last_ip VARCHAR(45),
            revoked_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    `);
    console.log('[Database] client_devices table checked/created.');

    await connection.query(`
        CREATE TABLE IF NOT EXISTS user_cloud_settings (
            user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
            cloud_sync_enabled BOOLEAN NOT NULL DEFAULT TRUE,
            auto_sync BOOLEAN NOT NULL DEFAULT TRUE,
            cross_platform_default BOOLEAN NOT NULL DEFAULT TRUE,
            sync_worlds_default BOOLEAN NOT NULL DEFAULT FALSE,
            sync_screenshots_default BOOLEAN NOT NULL DEFAULT FALSE,
            quota_bytes BIGINT NOT NULL DEFAULT 5368709120,
            max_instances INTEGER NOT NULL DEFAULT 10,
            used_bytes BIGINT NOT NULL DEFAULT 0,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    `);
    console.log('[Database] user_cloud_settings table checked/created.');

    await connection.query(`
        CREATE TABLE IF NOT EXISTS device_auth_codes (
            code_hash CHAR(64) PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            code_challenge VARCHAR(128) NOT NULL,
            device_name VARCHAR(100),
            platform VARCHAR(20),
            expires_at TIMESTAMPTZ NOT NULL,
            consumed_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    `);
    console.log('[Database] device_auth_codes table checked/created.');

    await connection.query('CREATE INDEX IF NOT EXISTS idx_client_devices_user ON client_devices(user_id)');
    await connection.query('CREATE INDEX IF NOT EXISTS idx_device_auth_codes_expiry ON device_auth_codes(expires_at)');

    return true;
};

const pruneDeviceAuthCodes = async () => {
    try {
        const [result] = await pool.query(
            `DELETE FROM device_auth_codes
              WHERE expires_at < NOW() - INTERVAL '1 hour'
                 OR consumed_at < NOW() - INTERVAL '1 hour'`
        );
        if (result && result.affectedRows > 0) {
            console.log(`[LuxCloud] Pruned ${result.affectedRows} expired device auth code(s).`);
        }
    } catch (err) {
        console.error('[LuxCloud] Failed to prune device auth codes:', err.message);
    }
};

module.exports = { createCloudTables, pruneDeviceAuthCodes };
