const pool = require('./database');

const createTables = async () => {
    let connection;
    try {
        connection = await pool.getConnection();

        await connection.query(`
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                google_id VARCHAR(255) UNIQUE NOT NULL,
                username VARCHAR(50) UNIQUE NOT NULL,
                email VARCHAR(100),
                avatar VARCHAR(1000),
                bio TEXT,
                role VARCHAR(20) NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
                last_login TIMESTAMPTZ,
                ip_address VARCHAR(45),
                banned BOOLEAN NOT NULL DEFAULT FALSE,
                ban_reason TEXT,
                ban_expires TIMESTAMPTZ,
                warn_count INTEGER NOT NULL DEFAULT 0,
                is_private BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        `);
        console.log('[Database] Users table checked/created.');

        await connection.query(`
            CREATE TABLE IF NOT EXISTS extensions (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                name VARCHAR(100) NOT NULL,
                identifier VARCHAR(100) UNIQUE,
                summary VARCHAR(255),
                description TEXT,
                type VARCHAR(20) NOT NULL DEFAULT 'extension' CHECK (type IN ('extension', 'theme')),
                visibility VARCHAR(20) NOT NULL DEFAULT 'public' CHECK (visibility IN ('public', 'unlisted')),
                file_path VARCHAR(255),
                banner_path VARCHAR(255),
                status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'action_required')),
                downloads INTEGER NOT NULL DEFAULT 0,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        `);
        console.log('[Database] Extensions table checked/created.');

        await connection.query(`
            CREATE TABLE IF NOT EXISTS extension_versions (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                extension_id INTEGER NOT NULL REFERENCES extensions(id) ON DELETE CASCADE,
                version VARCHAR(20) NOT NULL,
                changelog TEXT,
                file_path VARCHAR(255) NOT NULL,
                downloads INTEGER NOT NULL DEFAULT 0,
                status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'action_required')),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE (extension_id, version)
            )
        `);
        console.log('[Database] Extension versions table checked/created.');

        await connection.query(`
            CREATE TABLE IF NOT EXISTS extension_metadata_drafts (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                extension_id INTEGER NOT NULL REFERENCES extensions(id) ON DELETE CASCADE,
                name VARCHAR(100),
                summary VARCHAR(255),
                description TEXT,
                banner_path VARCHAR(255),
                status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'action_required')),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        `);
        console.log('[Database] Extension metadata drafts table checked/created.');

        await connection.query(`
            CREATE TABLE IF NOT EXISTS notifications (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                message TEXT NOT NULL,
                type VARCHAR(20) NOT NULL DEFAULT 'info' CHECK (type IN ('info', 'success', 'warning', 'error')),
                is_read BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        `);
        console.log('[Database] Notifications table checked/created.');

        await connection.query(`
            CREATE TABLE IF NOT EXISTS modpack_codes (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code VARCHAR(8) UNIQUE NOT NULL,
                owner_uuid VARCHAR(100),
                owner_ip VARCHAR(45),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        `);
        console.log('[Database] Modpack codes table checked/created.');

        // Fixed-list marketplace metadata. No CHECK constraint here (columns were added via
        // ALTER, not at CREATE TABLE time) — the allowed values are validated in server.js
        // against the same list the frontend dropdowns use (see CATEGORIES/MC_VERSIONS).
        await connection.query('ALTER TABLE extensions ADD COLUMN IF NOT EXISTS category VARCHAR(30)');
        await connection.query('ALTER TABLE extensions ADD COLUMN IF NOT EXISTS mc_version VARCHAR(20)');
        console.log('[Database] Extensions category/mc_version columns checked/added.');

        await connection.query(`
            CREATE TABLE IF NOT EXISTS extension_ratings (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                extension_id INTEGER NOT NULL REFERENCES extensions(id) ON DELETE CASCADE,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE (extension_id, user_id)
            )
        `);
        console.log('[Database] Extension ratings table checked/created.');

        await connection.query(`
            CREATE TABLE IF NOT EXISTS extension_comments (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                extension_id INTEGER NOT NULL REFERENCES extensions(id) ON DELETE CASCADE,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                content VARCHAR(1000) NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'visible' CHECK (status IN ('visible', 'hidden')),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        `);
        console.log('[Database] Extension comments table checked/created.');

        await connection.query(`
            CREATE TABLE IF NOT EXISTS content_reports (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                reporter_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                target_type VARCHAR(20) NOT NULL CHECK (target_type IN ('extension', 'comment')),
                target_id INTEGER NOT NULL,
                reason VARCHAR(500) NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'resolved', 'dismissed')),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE (reporter_user_id, target_type, target_id)
            )
        `);
        console.log('[Database] Content reports table checked/created.');

        await connection.query(`
            CREATE TABLE IF NOT EXISTS admin_audit_log (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                admin_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
                admin_label VARCHAR(100) NOT NULL,
                action VARCHAR(50) NOT NULL,
                target_type VARCHAR(30) NOT NULL,
                target_id VARCHAR(50),
                details TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        `);
        console.log('[Database] Admin audit log table checked/created.');

        await connection.query('CREATE INDEX IF NOT EXISTS idx_modpack_codes_owner_uuid ON modpack_codes(owner_uuid)');
        await connection.query('CREATE INDEX IF NOT EXISTS idx_modpack_codes_owner_ip ON modpack_codes(owner_ip)');
        await connection.query('CREATE INDEX IF NOT EXISTS idx_extensions_user_id ON extensions(user_id)');
        await connection.query('CREATE INDEX IF NOT EXISTS idx_extension_versions_extension_id ON extension_versions(extension_id)');
        await connection.query('CREATE INDEX IF NOT EXISTS idx_extension_ratings_extension_id ON extension_ratings(extension_id)');
        await connection.query('CREATE INDEX IF NOT EXISTS idx_extension_comments_extension_id ON extension_comments(extension_id)');
        await connection.query('CREATE INDEX IF NOT EXISTS idx_content_reports_status ON content_reports(status)');
        await connection.query('CREATE INDEX IF NOT EXISTS idx_admin_audit_log_created_at ON admin_audit_log(created_at)');

        await connection.query(`
            CREATE OR REPLACE FUNCTION set_updated_at()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.updated_at = NOW();
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
        `);
        await connection.query('DROP TRIGGER IF EXISTS extensions_set_updated_at ON extensions');
        await connection.query(`
            CREATE TRIGGER extensions_set_updated_at
            BEFORE UPDATE ON extensions
            FOR EACH ROW
            EXECUTE FUNCTION set_updated_at();
        `);

        // Legacy compatibility: if extensions.file_path exists, ensure a 1.0.0 version row exists.
        const [extensions] = await connection.query(`
            SELECT id, file_path, status, downloads, created_at
            FROM extensions
            WHERE file_path IS NOT NULL AND file_path <> ''
        `);

        for (const ext of extensions) {
            const [versions] = await connection.query(
                'SELECT id FROM extension_versions WHERE extension_id = ? AND version = ?',
                [ext.id, '1.0.0']
            );
            if (versions.length === 0) {
                await connection.query(
                    'INSERT INTO extension_versions (extension_id, version, changelog, file_path, downloads, status, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)',
                    [ext.id, '1.0.0', 'Initial upload', ext.file_path, ext.downloads || 0, ext.status || 'pending', ext.created_at || new Date()]
                );
            }
        }

        return true;
    } catch (err) {
        console.error('[Database] Error initializing tables:', err);
        return false;
    } finally {
        if (connection) connection.release();
    }
};

module.exports = { createTables };

if (require.main === module) {
    createTables().then(success => {
        process.exit(success ? 0 : 1);
    });
}
