// Tables for the Lux Client mod cosmetics (capes, name styles) and the cape marketplace.
// Timestamps are stored as epoch milliseconds (BIGINT) so the API can compare them cheaply.

async function createLuxTables(connection) {
    // A Minecraft account that has signed in through the Lux Client mod.
    // user_id links it to a website account (Google sign-in) once the player links it.
    await connection.query(`
        CREATE TABLE IF NOT EXISTS lux_players (
            uuid VARCHAR(32) PRIMARY KEY,
            name VARCHAR(16) NOT NULL,
            user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
            cape TEXT,
            name_style TEXT,
            last_seen BIGINT NOT NULL DEFAULT 0,
            created_at BIGINT NOT NULL DEFAULT 0
        )
    `);
    await connection.query('CREATE INDEX IF NOT EXISTS idx_lux_players_user_id ON lux_players(user_id)');
    await connection.query('ALTER TABLE lux_players ADD COLUMN IF NOT EXISTS cosmetics TEXT');

    // Mod sessions. Only the sha256 of the token is stored.
    await connection.query(`
        CREATE TABLE IF NOT EXISTS lux_tokens (
            token_hash VARCHAR(64) PRIMARY KEY,
            uuid VARCHAR(32) NOT NULL,
            expires BIGINT NOT NULL
        )
    `);

    // Every uploaded cape picture. Nobody but the uploader and admins can see it
    // until an admin has approved it.
    await connection.query(`
        CREATE TABLE IF NOT EXISTS lux_cape_images (
            hash VARCHAR(64) PRIMARY KEY,
            width INTEGER NOT NULL,
            height INTEGER NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
            owner_uuid VARCHAR(32),
            owner_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
            reject_reason TEXT,
            reviewed_by INTEGER,
            reviewed_at BIGINT,
            created_at BIGINT NOT NULL DEFAULT 0
        )
    `);
    await connection.query('CREATE INDEX IF NOT EXISTS idx_lux_cape_images_status ON lux_cape_images(status)');
    // Everybody who uploaded a picture (the same picture can come from several players).
    await connection.query(`
        CREATE TABLE IF NOT EXISTS lux_image_uploads (
            hash VARCHAR(64) NOT NULL,
            uuid VARCHAR(32) NOT NULL,
            PRIMARY KEY (hash, uuid)
        )
    `);

    // Marketplace listings (uploaded on the website with a website account).
    await connection.query(`
        CREATE TABLE IF NOT EXISTS lux_capes (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            title VARCHAR(40) NOT NULL,
            image_hash VARCHAR(64) NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
            reject_reason TEXT,
            uses INTEGER NOT NULL DEFAULT 0,
            created_at BIGINT NOT NULL DEFAULT 0,
            reviewed_at BIGINT
        )
    `);
    await connection.query('CREATE INDEX IF NOT EXISTS idx_lux_capes_status ON lux_capes(status)');
    await connection.query('CREATE INDEX IF NOT EXISTS idx_lux_capes_user_id ON lux_capes(user_id)');
    console.log('[Database] Lux cosmetics tables checked/created.');
}

module.exports = { createLuxTables };
