const pool = require('./database');

const createCloudTables = async (connection) => {
    await connection.query(`
        CREATE TABLE IF NOT EXISTS client_devices (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            device_uuid VARCHAR(64) UNIQUE NOT NULL,
            name VARCHAR(100),
            platform VARCHAR(20) NOT NULL,
            app_version VARCHAR(20),
            refresh_token_hash CHAR(64),
            refresh_expires_at TIMESTAMPTZ,
            prev_refresh_token_hash CHAR(64),
            prev_refresh_valid_until TIMESTAMPTZ,
            token_generation INTEGER NOT NULL DEFAULT 1,
            last_seen_at TIMESTAMPTZ,
            last_ip VARCHAR(45),
            revoked_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    `);
    console.log('[Database] client_devices table checked/created.');

    await connection.query(`
        CREATE TABLE IF NOT EXISTS user_cloud_settings (
            user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
            cloud_sync_enabled BOOLEAN NOT NULL DEFAULT TRUE,
            auto_sync BOOLEAN NOT NULL DEFAULT TRUE,
            cross_platform_default BOOLEAN NOT NULL DEFAULT TRUE,
            sync_worlds_default BOOLEAN NOT NULL DEFAULT FALSE,
            sync_screenshots_default BOOLEAN NOT NULL DEFAULT FALSE,
            quota_bytes BIGINT NOT NULL DEFAULT 5368709120,
            max_instances INTEGER NOT NULL DEFAULT 10,
            used_bytes BIGINT NOT NULL DEFAULT 0,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    `);
    console.log('[Database] user_cloud_settings table checked/created.');

    await connection.query(`
        CREATE TABLE IF NOT EXISTS device_auth_codes (
            code_hash CHAR(64) PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            code_challenge VARCHAR(128) NOT NULL,
            device_name VARCHAR(100),
            platform VARCHAR(20),
            expires_at TIMESTAMPTZ NOT NULL,
            consumed_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    `);
    console.log('[Database] device_auth_codes table checked/created.');

    await connection.query(`
        CREATE TABLE IF NOT EXISTS cloud_instances (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            instance_uuid VARCHAR(64) NOT NULL,
            name VARCHAR(120) NOT NULL,
            icon_blob CHAR(64),
            mc_version VARCHAR(32),
            loader VARCHAR(32),
            loader_version VARCHAR(48),
            current_revision INTEGER NOT NULL DEFAULT 0,
            origin_platform VARCHAR(20),
            cross_platform BOOLEAN NOT NULL DEFAULT TRUE,
            sync_worlds BOOLEAN NOT NULL DEFAULT FALSE,
            sync_screenshots BOOLEAN NOT NULL DEFAULT FALSE,
            logical_bytes BIGINT NOT NULL DEFAULT 0,
            status VARCHAR(16) NOT NULL DEFAULT 'active'
                CHECK (status IN ('active', 'trashed')),
            last_touched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            last_pulled_at TIMESTAMPTZ,
            expiry_warned_at TIMESTAMPTZ,
            trashed_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (user_id, instance_uuid)
        )
    `);
    console.log('[Database] cloud_instances table checked/created.');

    await connection.query(`
        CREATE TABLE IF NOT EXISTS cloud_revisions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            instance_id INTEGER NOT NULL REFERENCES cloud_instances(id) ON DELETE CASCADE,
            revision INTEGER NOT NULL,
            parent_revision INTEGER,
            manifest_blob CHAR(64) NOT NULL,
            device_id INTEGER REFERENCES client_devices(id) ON DELETE SET NULL,
            entry_count INTEGER NOT NULL DEFAULT 0,
            logical_bytes BIGINT NOT NULL DEFAULT 0,
            has_worlds BOOLEAN NOT NULL DEFAULT FALSE,
            label VARCHAR(120),
            keep_until TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (instance_id, revision)
        )
    `);
    console.log('[Database] cloud_revisions table checked/created.');

    await connection.query(`
        CREATE TABLE IF NOT EXISTS blobs (
            hash CHAR(64) PRIMARY KEY,
            size BIGINT NOT NULL,
            stored_size BIGINT NOT NULL,
            compression VARCHAR(8) NOT NULL DEFAULT 'none',
            storage_key VARCHAR(160) NOT NULL,
            is_chunk_list BOOLEAN NOT NULL DEFAULT FALSE,
            refcount INTEGER NOT NULL DEFAULT 0,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            last_referenced_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    `);
    console.log('[Database] blobs table checked/created.');

    await connection.query(`
        CREATE TABLE IF NOT EXISTS blob_refs (
            revision_id INTEGER NOT NULL REFERENCES cloud_revisions(id) ON DELETE CASCADE,
            blob_hash CHAR(64) NOT NULL REFERENCES blobs(hash) ON DELETE RESTRICT,
            PRIMARY KEY (revision_id, blob_hash)
        )
    `);
    console.log('[Database] blob_refs table checked/created.');

    await connection.query(`
        CREATE TABLE IF NOT EXISTS blob_gc_queue (
            blob_hash CHAR(64) PRIMARY KEY,
            eligible_at TIMESTAMPTZ NOT NULL,
            attempts INTEGER NOT NULL DEFAULT 0
        )
    `);
    console.log('[Database] blob_gc_queue table checked/created.');

    await connection.query(`
        CREATE TABLE IF NOT EXISTS cloud_instance_playtime (
            instance_id INTEGER NOT NULL REFERENCES cloud_instances(id) ON DELETE CASCADE,
            device_id INTEGER NOT NULL REFERENCES client_devices(id) ON DELETE CASCADE,
            total_ms BIGINT NOT NULL DEFAULT 0,
            last_session_id VARCHAR(32),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            PRIMARY KEY (instance_id, device_id)
        )
    `);
    console.log('[Database] cloud_instance_playtime table checked/created.');

    await connection.query(`
        CREATE TABLE IF NOT EXISTS cloud_sessions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            instance_id INTEGER NOT NULL REFERENCES cloud_instances(id) ON DELETE CASCADE,
            device_id INTEGER NOT NULL REFERENCES client_devices(id) ON DELETE CASCADE,
            session_uuid VARCHAR(32) UNIQUE NOT NULL,
            started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            last_heartbeat_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            ended_at TIMESTAMPTZ
        )
    `);
    console.log('[Database] cloud_sessions table checked/created.');

    await connection.query(`
        CREATE TABLE IF NOT EXISTS blob_upload_claims (
            blob_hash CHAR(64) NOT NULL,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            device_id INTEGER REFERENCES client_devices(id) ON DELETE SET NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            PRIMARY KEY (blob_hash, user_id)
        )
    `);
    console.log('[Database] blob_upload_claims table checked/created.');

    await connection.query('CREATE INDEX IF NOT EXISTS idx_client_devices_user ON client_devices(user_id)');
    await connection.query('CREATE INDEX IF NOT EXISTS idx_device_auth_codes_expiry ON device_auth_codes(expires_at)');
    await connection.query('CREATE INDEX IF NOT EXISTS idx_cloud_instances_user ON cloud_instances(user_id)');
    await connection.query('CREATE INDEX IF NOT EXISTS idx_cloud_instances_expiry ON cloud_instances(status, last_touched_at)');
    await connection.query('CREATE INDEX IF NOT EXISTS idx_cloud_revisions_instance ON cloud_revisions(instance_id, revision DESC)');
    await connection.query('CREATE INDEX IF NOT EXISTS idx_blob_refs_hash ON blob_refs(blob_hash)');
    await connection.query('CREATE INDEX IF NOT EXISTS idx_blobs_refcount ON blobs(refcount) WHERE refcount = 0');
    await connection.query('CREATE INDEX IF NOT EXISTS idx_cloud_sessions_active ON cloud_sessions(instance_id) WHERE ended_at IS NULL');
    await connection.query('CREATE INDEX IF NOT EXISTS idx_blob_upload_claims_age ON blob_upload_claims(created_at)');

    return true;
};

const pruneDeviceAuthCodes = async () => {
    try {
        const [result] = await pool.query(
            `DELETE FROM device_auth_codes
              WHERE expires_at < NOW() - INTERVAL '1 hour'
                 OR consumed_at < NOW() - INTERVAL '1 hour'`
        );
        if (result && result.affectedRows > 0) {
            console.log(`[LuxCloud] Pruned ${result.affectedRows} expired device auth code(s).`);
        }
    } catch (err) {
        console.error('[LuxCloud] Failed to prune device auth codes:', err.message);
    }
};

module.exports = { createCloudTables, pruneDeviceAuthCodes };
