const path = require('path');
const crypto = require('crypto');
const Module = require('module');

const SITE = path.resolve(__dirname, '..');

process.env.NODE_ENV = 'test';
process.env.LUXCLOUD_JWT_SECRET = 'a'.repeat(48);
process.env.LUXCLOUD_ACCESS_TTL_SECONDS = '2';
process.env.LUXCLOUD_REFRESH_GRACE_MS = '30000';
const { newDb } = require('pg-mem');
const db = newDb({ autoCreateForeignKeyIndices: true });

db.public.registerFunction({ name: 'version', returns: 'text', implementation: () => 'PostgreSQL 14 (pg-mem)' });

const pgAdapter = db.adapters.createPg();

const originalLoad = Module._load;
Module._load = function (request, parent, isMain) {
    if (request === 'pg') return pgAdapter;
    if (request === 'dotenv') return { config: () => ({}) };
    return originalLoad.call(this, request, parent, isMain);
};

const express = require('express');
const bodyParser = require('body-parser');
const pool = require(path.join(SITE, 'database.js'));
const { createCloudTables } = require(path.join(SITE, 'db_init_cloud.js'));

async function setupSchema() {
    const connection = await pool.getConnection();
    await connection.query(`
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            google_id VARCHAR(255) UNIQUE NOT NULL,
            username VARCHAR(50) UNIQUE NOT NULL,
            email VARCHAR(100),
            avatar VARCHAR(1000),
            role VARCHAR(20) NOT NULL DEFAULT 'user',
            banned BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    `);
    await connection.query(`
        CREATE TABLE IF NOT EXISTS notifications (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            message TEXT NOT NULL,
            type VARCHAR(20) NOT NULL DEFAULT 'info',
            is_read BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    `);
    await createCloudTables(connection);
    connection.release();

    await pool.query(
        'INSERT INTO users (google_id, username, email, avatar) VALUES (?, ?, ?, ?)',
        ['g-1', 'beatv', 'beatv@example.com', 'https://example.com/a.png']
    );
    await pool.query(
        'INSERT INTO users (google_id, username, email, banned) VALUES (?, ?, ?, ?)',
        ['g-2', 'bannedguy', 'b@example.com', true]
    );
}

let sessionUser = null;

function buildApp() {
    const app = express();
    app.set('trust proxy', 1);
    app.use(bodyParser.json());
    app.use((req, _res, next) => {
        req.user = sessionUser || undefined;
        req.isAuthenticated = () => Boolean(sessionUser);
        next();
    });
    app.use('/', require(path.join(SITE, 'routes', 'deviceAuth.js')));
    app.use('/api/cloud', require(path.join(SITE, 'routes', 'cloud.js')));
    return app;
}

const http = require('http');

function request(server, { method = 'GET', url, body, token, headers = {} }) {
    return new Promise((resolve, reject) => {
        const payload = body === undefined ? null : JSON.stringify(body);
        const req = http.request({
            host: '127.0.0.1',
            port: server.address().port,
            method,
            path: url,
            headers: {
                ...(payload ? { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(payload) } : {}),
                ...(token ? { Authorization: `Bearer ${token}` } : {}),
                ...headers
            }
        }, (res) => {
            let raw = '';
            res.on('data', (c) => { raw += c; });
            res.on('end', () => {
                let parsed = null;
                try { parsed = raw ? JSON.parse(raw) : null; } catch { parsed = raw; }
                resolve({ status: res.statusCode, headers: res.headers, body: parsed });
            });
        });
        req.on('error', reject);
        if (payload) req.write(payload);
        req.end();
    });
}

let passed = 0;
let failed = 0;

function check(name, condition, detail) {
    if (condition) {
        passed += 1;
        console.log(`  PASS  ${name}`);
    } else {
        failed += 1;
        console.log(`  FAIL  ${name}${detail ? `  -> ${JSON.stringify(detail)}` : ''}`);
    }
}

function base64Url(buffer) {
    return buffer.toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

function pkce() {
    const verifier = base64Url(crypto.randomBytes(32));
    const challenge = base64Url(crypto.createHash('sha256').update(verifier).digest());
    return { verifier, challenge };
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function approve(server, { challenge, state, deviceName = 'DESKTOP-TEST', platform = 'win32' }) {
    return request(server, {
        method: 'POST',
        url: '/auth/device/approve',
        body: { code_challenge: challenge, state, device_name: deviceName, platform }
    });
}

function codeFrom(redirectUrl) {
    return new URL(redirectUrl).searchParams.get('code');
}

async function main() {
    await setupSchema();
    const app = buildApp();
    const server = app.listen(0);
    await new Promise((r) => server.once('listening', r));

    const state = base64Url(crypto.randomBytes(16));

    console.log('\n1) Zustimmungsseite und Codeausgabe');
    sessionUser = null;
    let res = await request(server, { url: `/auth/device?code_challenge=${pkce().challenge}&state=${state}` });
    check('anonym -> Redirect auf Google-Login', res.status === 302 && res.headers.location.startsWith('/auth/google?returnTo='), res.headers.location);

    res = await request(server, { url: `/auth/device?code_challenge=short&state=${state}` });
    check('kaputte Parameter -> 400', res.status === 400, res.body);

    sessionUser = { id: 1, username: 'beatv', role: 'user', banned: false };
    const p1 = pkce();
    res = await request(server, { url: `/auth/device?code_challenge=${p1.challenge}&state=${state}&device_name=DESKTOP-TEST&platform=win32` });
    check('angemeldet -> Redirect auf die SPA-Seite', res.status === 302 && res.headers.location.startsWith('/authorize-device?'), res.headers.location);

    res = await approve(server, { challenge: p1.challenge, state });
    check('approve liefert eine luxclient://auth URL', res.status === 200 && String(res.body.redirectUrl).startsWith('luxclient://auth?code='), res.body);
    const code1 = codeFrom(res.body.redirectUrl);

    res = await request(server, {
        method: 'POST',
        url: '/auth/device/approve',
        body: { code_challenge: p1.challenge, state },
        headers: { Origin: 'https://evil.example.com' }
    });
    check('approve von fremder Origin -> 403', res.status === 403, res.body);

    console.log('\n2) Token-Tausch');
    res = await request(server, {
        method: 'POST',
        url: '/api/auth/device/token',
        body: { code: code1, code_verifier: base64Url(crypto.randomBytes(32)), device_uuid: 'dev-aaaaaaaa-1', platform: 'win32' }
    });
    check('falscher code_verifier -> invalid_grant', res.status === 400 && res.body.error === 'invalid_grant', res.body);

    const p2 = pkce();
    res = await approve(server, { challenge: p2.challenge, state });
    const code2 = codeFrom(res.body.redirectUrl);

    res = await request(server, {
        method: 'POST',
        url: '/api/auth/device/token',
        body: { code: code2, code_verifier: p2.verifier, device_uuid: 'dev-aaaaaaaa-1', device_name: 'DESKTOP-TEST', platform: 'win32', app_version: '1.11.0' }
    });
    check('gueltiger Tausch -> Tokenpaar', res.status === 200 && res.body.accessToken && res.body.refreshToken, res.body);
    check('Antwort enthaelt den User', res.body.user && res.body.user.username === 'beatv', res.body.user);
    let access = res.body.accessToken;
    let refresh = res.body.refreshToken;

    res = await request(server, {
        method: 'POST',
        url: '/api/auth/device/token',
        body: { code: code2, code_verifier: p2.verifier, device_uuid: 'dev-aaaaaaaa-2', platform: 'win32' }
    });
    check('derselbe Code ein zweites Mal -> invalid_grant', res.status === 400 && res.body.error === 'invalid_grant', res.body);

    console.log('\n3) Konto und Geraete');
    res = await request(server, { url: '/api/cloud/me', token: access });
    check('GET /me -> 200', res.status === 200, res.body);
    check('/me liefert Standardkontingent 5 GiB / 10 Instanzen',
        res.body.quota && res.body.quota.quotaBytes === 5368709120 && res.body.quota.maxInstances === 10, res.body.quota);
    check('/me liefert die Standardeinstellungen',
        res.body.settings && res.body.settings.cloudSyncEnabled === true && res.body.settings.syncWorldsDefault === false, res.body.settings);

    res = await request(server, { url: '/api/cloud/me' });
    check('GET /me ohne Token -> 401 unauthorized', res.status === 401 && res.body.error === 'unauthorized', res.body);

    res = await request(server, { method: 'PATCH', url: '/api/cloud/me/settings', token: access, body: { syncWorldsDefault: true } });
    check('PATCH settings speichert', res.status === 200 && res.body.settings.syncWorldsDefault === true, res.body);

    res = await request(server, { method: 'PATCH', url: '/api/cloud/me/settings', token: access, body: { syncWorldsDefault: 'yes' } });
    check('PATCH settings mit falschem Typ -> 400', res.status === 400, res.body);

    res = await request(server, { url: '/api/cloud/devices', token: access });
    check('GET /devices listet genau dieses Geraet',
        res.status === 200 && res.body.devices.length === 1 && res.body.devices[0].isCurrent === true, res.body);

    console.log('\n4) Isolation zwischen Konten');
    sessionUser = { id: 2, username: 'bannedguy', role: 'user', banned: true };
    const p3 = pkce();
    res = await approve(server, { challenge: p3.challenge, state });
    check('gebannter User bekommt keinen Code -> 403', res.status === 403, res.body);

    await pool.query('UPDATE users SET banned = ? WHERE id = ?', [false, 2]);
    sessionUser = { id: 2, username: 'bannedguy', role: 'user', banned: false };
    const p4 = pkce();
    res = await approve(server, { challenge: p4.challenge, state, deviceName: 'LAPTOP-B' });
    const code4 = codeFrom(res.body.redirectUrl);

    res = await request(server, {
        method: 'POST',
        url: '/api/auth/device/token',
        body: { code: code4, code_verifier: p4.verifier, device_uuid: 'dev-aaaaaaaa-1', platform: 'linux' }
    });
    check('fremde Geraete-ID -> device_conflict', res.status === 409 && res.body.error === 'device_conflict', res.body);

    res = await request(server, {
        method: 'POST',
        url: '/api/auth/device/token',
        body: { code: code4, code_verifier: p4.verifier, device_uuid: 'dev-bbbbbbbb-1', platform: 'linux' }
    });
    check('nach device_conflict ist derselbe Code noch gueltig', res.status === 200 && Boolean(res.body.accessToken), res.body);
    const accessB = res.body.accessToken;

    res = await request(server, { url: '/api/cloud/devices', token: accessB });
    check('User B sieht nur sein eigenes Geraet',
        res.status === 200 && res.body.devices.length === 1 && res.body.devices[0].name === 'LAPTOP-B', res.body);

    res = await request(server, { method: 'DELETE', url: '/api/cloud/devices/dev-aaaaaaaa-1', token: accessB });
    check('User B kann das Geraet von User A nicht abmelden -> 404', res.status === 404 && res.body.error === 'not_found', res.body);

    res = await request(server, { url: '/api/cloud/me', token: accessB });
    check('User B sieht sein eigenes Konto', res.status === 200 && res.body.user.username === 'bannedguy', res.body.user);
    check('Einstellung von User A ist bei B nicht sichtbar', res.body.settings.syncWorldsDefault === false, res.body.settings);

    console.log('\n5) Refresh, Rotation und Reuse-Erkennung');
    res = await request(server, { method: 'POST', url: '/api/auth/device/refresh', body: { refresh_token: refresh, device_uuid: 'dev-aaaaaaaa-1' } });
    check('Refresh liefert ein neues Paar', res.status === 200 && res.body.refreshToken !== refresh, res.body);
    const refresh2 = res.body.refreshToken;
    const access2 = res.body.accessToken;

    res = await request(server, { method: 'POST', url: '/api/auth/device/refresh', body: { refresh_token: refresh, device_uuid: 'dev-aaaaaaaa-1' } });
    check('alter Token im Gnadenfenster wird noch akzeptiert', res.status === 200, res.body);
    const refresh3 = res.body.refreshToken;

    await pool.query('UPDATE client_devices SET prev_refresh_valid_until = NOW() - INTERVAL \'1 minute\' WHERE device_uuid = ?', ['dev-aaaaaaaa-1']);
    res = await request(server, { method: 'POST', url: '/api/auth/device/refresh', body: { refresh_token: refresh2, device_uuid: 'dev-aaaaaaaa-1' } });
    check('verbrauchter Token nach dem Gnadenfenster -> device_revoked', res.status === 401 && res.body.error === 'device_revoked', res.body);

    const [notes] = await pool.query('SELECT message, type FROM notifications WHERE user_id = ?', [1]);
    check('Reuse erzeugt eine Notification', notes.length === 1 && notes[0].type === 'warning', notes);

    res = await request(server, { url: '/api/cloud/me', token: access2 });
    check('nach der Reuse-Erkennung sind alte Access-Tokens tot', res.status === 401 && res.body.error === 'device_revoked', res.body);

    res = await request(server, { method: 'POST', url: '/api/auth/device/refresh', body: { refresh_token: refresh3, device_uuid: 'dev-aaaaaaaa-1' } });
    check('auch der zuletzt gueltige Token faellt mit der Kette', res.status === 401, res.body);

    console.log('\n6) Ablauf und Abmelden');
    sessionUser = { id: 1, username: 'beatv', role: 'user', banned: false };
    const p5 = pkce();
    res = await approve(server, { challenge: p5.challenge, state });
    const code5 = codeFrom(res.body.redirectUrl);
    res = await request(server, {
        method: 'POST',
        url: '/api/auth/device/token',
        body: { code: code5, code_verifier: p5.verifier, device_uuid: 'dev-aaaaaaaa-1', platform: 'win32' }
    });
    check('Neuanmeldung eines abgemeldeten Geraets funktioniert', res.status === 200 && Boolean(res.body.accessToken), res.body);
    const accessC = res.body.accessToken;

    res = await request(server, { url: '/api/cloud/me', token: accessC });
    check('neues Token wird akzeptiert', res.status === 200, res.body);

    console.log('     ... warte auf den Ablauf des Access-Tokens (2 s)');
    await sleep(2500);
    res = await request(server, { url: '/api/cloud/me', token: accessC });
    check('abgelaufenes Token -> token_expired', res.status === 401 && res.body.error === 'token_expired', res.body);

    const [devRow] = await pool.query('SELECT refresh_token_hash FROM client_devices WHERE device_uuid = ?', ['dev-aaaaaaaa-1']);
    check('Refresh-Token liegt nur als Hash in der DB',
        devRow[0] && /^[0-9a-f]{64}$/.test(devRow[0].refresh_token_hash), devRow[0]);

    const p6 = pkce();
    res = await approve(server, { challenge: p6.challenge, state });
    const code6 = codeFrom(res.body.redirectUrl);
    res = await request(server, {
        method: 'POST',
        url: '/api/auth/device/token',
        body: { code: code6, code_verifier: p6.verifier, device_uuid: 'dev-aaaaaaaa-1', platform: 'win32' }
    });
    const accessD = res.body.accessToken;

    res = await request(server, { method: 'POST', url: '/api/auth/device/revoke', token: accessD });
    check('revoke -> 200', res.status === 200, res.body);

    res = await request(server, { url: '/api/cloud/me', token: accessD });
    check('nach revoke ist das Token wertlos', res.status === 401 && res.body.error === 'device_revoked', res.body);

    console.log('\n7) Gebannte Konten');
    sessionUser = { id: 2, username: 'bannedguy', role: 'user', banned: false };
    const p7 = pkce();
    res = await approve(server, { challenge: p7.challenge, state, deviceName: 'LAPTOP-B' });
    const code7 = codeFrom(res.body.redirectUrl);
    res = await request(server, {
        method: 'POST',
        url: '/api/auth/device/token',
        body: { code: code7, code_verifier: p7.verifier, device_uuid: 'dev-bbbbbbbb-1', platform: 'linux' }
    });
    const accessB2 = res.body.accessToken;

    await pool.query('UPDATE users SET banned = ? WHERE id = ?', [true, 2]);
    res = await request(server, { url: '/api/cloud/me', token: accessB2 });
    check('gebannter User -> 403 forbidden', res.status === 403 && res.body.error === 'forbidden', res.body);

    res = await request(server, {
        method: 'POST',
        url: '/api/auth/device/refresh',
        body: { refresh_token: 'irrelevant', device_uuid: 'dev-bbbbbbbb-1' }
    });
    check('Refresh eines gebannten Kontos -> 403', res.status === 403 && res.body.error === 'forbidden', res.body);

    server.close();

    console.log(`\n=== ${passed} bestanden, ${failed} fehlgeschlagen ===`);
    process.exit(failed === 0 ? 0 : 1);
}

main().catch((err) => {
    console.error('\nTEST HARNESS ERROR:', err);
    process.exit(2);
});
