const path = require('path');
const crypto = require('crypto');
const fs = require('fs');
const http = require('http');
const os = require('os');
const Module = require('module');

const SITE = path.resolve(__dirname, '..');

function bootEnv({ accessTtlSeconds = 3600, storageRoot } = {}) {
    process.env.NODE_ENV = 'test';
    process.env.LUXCLOUD_JWT_SECRET = 'a'.repeat(48);
    process.env.LUXCLOUD_ACCESS_TTL_SECONDS = String(accessTtlSeconds);
    process.env.LUXCLOUD_REFRESH_GRACE_MS = '30000';
    process.env.LUXCLOUD_STORAGE_DRIVER = 'fs';
    process.env.LUXCLOUD_FS_ROOT = path.join(storageRoot, 'blobs');
    process.env.LUXCLOUD_STAGING_DIR = path.join(storageRoot, 'staging');
    process.env.LUXCLOUD_GC_DRY_RUN = 'false';

    const { newDb } = require('pg-mem');
    const db = newDb({ autoCreateForeignKeyIndices: true });
    db.public.registerFunction({
        name: 'version',
        returns: 'text',
        implementation: () => 'PostgreSQL 14 (pg-mem)'
    });

    const pgAdapter = db.adapters.createPg();
    const originalLoad = Module._load;
    Module._load = function (request, parent, isMain) {
        if (request === 'pg') return pgAdapter;
        if (request === 'dotenv') return { config: () => ({}) };
        return originalLoad.call(this, request, parent, isMain);
    };

    return db;
}

function base64Url(buffer) {
    return buffer.toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

function pkce() {
    const verifier = base64Url(crypto.randomBytes(32));
    const challenge = base64Url(crypto.createHash('sha256').update(verifier).digest());
    return { verifier, challenge };
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

class Harness {
    constructor(options = {}) {
        this.storageRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'luxcloud-test-'));
        this.db = bootEnv({ ...options, storageRoot: this.storageRoot });
        require(path.join(SITE, 'storage')).resetStorage();
        this.pool = require(path.join(SITE, 'database.js'));
        this.sessionUser = null;
        this.passed = 0;
        this.failed = 0;
        this.server = null;
    }

    async createSchema() {
        const connection = await this.pool.getConnection();
        await connection.query(`
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                google_id VARCHAR(255) UNIQUE NOT NULL,
                username VARCHAR(50) UNIQUE NOT NULL,
                email VARCHAR(100),
                avatar VARCHAR(1000),
                role VARCHAR(20) NOT NULL DEFAULT 'user',
                banned BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        `);
        await connection.query(`
            CREATE TABLE IF NOT EXISTS notifications (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                message TEXT NOT NULL,
                type VARCHAR(20) NOT NULL DEFAULT 'info',
                is_read BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        `);
        await connection.query(`
            CREATE TABLE IF NOT EXISTS admin_audit_log (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                admin_user_id INTEGER,
                admin_label VARCHAR(100),
                action VARCHAR(100) NOT NULL,
                target_type VARCHAR(50),
                target_id VARCHAR(100),
                details TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        `);
        const { createCloudTables } = require(path.join(SITE, 'db_init_cloud.js'));
        await createCloudTables(connection);
        connection.release();
    }

    async createUser({ googleId, username, email = null, avatar = null, banned = false }) {
        const [result] = await this.pool.query(
            'INSERT INTO users (google_id, username, email, avatar, banned) VALUES (?, ?, ?, ?, ?)',
            [googleId, username, email, avatar, banned]
        );
        return result.insertId;
    }

    async start(options = {}) {
        await this.createSchema();

        const express = require('express');
        const bodyParser = require('body-parser');

        const app = express();
        app.set('trust proxy', 1);
        app.use(bodyParser.json());
        app.use((req, _res, next) => {
            req.user = this.sessionUser || undefined;
            req.isAuthenticated = () => Boolean(this.sessionUser);
            next();
        });
        app.use('/', require(path.join(SITE, 'routes', 'deviceAuth.js')));
        app.use('/', require(path.join(SITE, 'routes', 'devicePairing.js')));
        app.use('/api/cloud', require(path.join(SITE, 'routes', 'cloud.js')));
        app.use('/api/cloud', require(path.join(SITE, 'routes', 'cloudBlobs.js')));
        app.use('/api/cloud', require(path.join(SITE, 'routes', 'cloudSync.js')));
        app.use('/api/admin/cloud', require(path.join(SITE, 'routes', 'adminCloud.js')));

        this.server = app.listen(0);
        await new Promise((r) => this.server.once('listening', r));
        return this.server;
    }

    stop() {
        if (this.server) this.server.close();
        try {
            fs.rmSync(this.storageRoot, { recursive: true, force: true });
        } catch {
            this.storageRoot = null;
        }
    }

    setSessionUser(user) {
        this.sessionUser = user;
    }

    request({ method = 'GET', url, body, token, headers = {}, raw = false }) {
        return new Promise((resolve, reject) => {
            const isRaw = Buffer.isBuffer(body);
            const payload = body === undefined ? null : (isRaw ? body : JSON.stringify(body));
            const req = http.request({
                host: '127.0.0.1',
                port: this.server.address().port,
                method,
                path: url,
                headers: {
                    ...(payload
                        ? {
                            ...(isRaw ? {} : { 'Content-Type': 'application/json' }),
                            'Content-Length': Buffer.byteLength(payload)
                        }
                        : {}),
                    ...(token ? { Authorization: `Bearer ${token}` } : {}),
                    ...headers
                }
            }, (res) => {
                const chunks = [];
                res.on('data', (c) => chunks.push(c));
                res.on('end', () => {
                    const buffer = Buffer.concat(chunks);
                    if (raw) {
                        resolve({ status: res.statusCode, headers: res.headers, body: buffer });
                        return;
                    }
                    const text = buffer.toString('utf8');
                    let parsed = null;
                    try { parsed = text ? JSON.parse(text) : null; } catch { parsed = text; }
                    resolve({ status: res.statusCode, headers: res.headers, body: parsed });
                });
            });
            req.on('error', reject);
            if (payload) req.write(payload);
            req.end();
        });
    }

    async approve({ challenge, state, deviceName = 'DESKTOP-TEST', platform = 'win32' }) {
        return this.request({
            method: 'POST',
            url: '/auth/device/approve',
            body: { code_challenge: challenge, state, device_name: deviceName, platform }
        });
    }

    codeFrom(redirectUrl) {
        return new URL(redirectUrl).searchParams.get('code');
    }

    async authorizeDevice({ user, deviceUuid, deviceName = 'DESKTOP-TEST', platform = 'win32', appVersion }) {
        const previousSession = this.sessionUser;
        this.setSessionUser(user);

        const pair = pkce();
        const state = base64Url(crypto.randomBytes(16));
        const approved = await this.approve({ challenge: pair.challenge, state, deviceName, platform });
        if (approved.status !== 200) {
            this.setSessionUser(previousSession);
            throw new Error(`approve failed: ${JSON.stringify(approved.body)}`);
        }

        const tokens = await this.request({
            method: 'POST',
            url: '/api/auth/device/token',
            body: {
                code: this.codeFrom(approved.body.redirectUrl),
                code_verifier: pair.verifier,
                device_uuid: deviceUuid,
                device_name: deviceName,
                platform,
                app_version: appVersion
            }
        });

        this.setSessionUser(previousSession);
        if (tokens.status !== 200) {
            throw new Error(`token exchange failed: ${JSON.stringify(tokens.body)}`);
        }
        return tokens.body;
    }

    check(name, condition, detail) {
        if (condition) {
            this.passed += 1;
            console.log(`  PASS  ${name}`);
        } else {
            this.failed += 1;
            console.log(`  FAIL  ${name}${detail !== undefined ? `  -> ${JSON.stringify(detail)}` : ''}`);
        }
    }

    section(title) {
        console.log(`\n${title}`);
    }

    finish() {
        this.stop();
        console.log(`\n=== ${this.passed} bestanden, ${this.failed} fehlgeschlagen ===`);
        process.exit(this.failed === 0 ? 0 : 1);
    }
}

module.exports = { Harness, base64Url, pkce, sleep };
