// Live codes: admins can keep one share code and change what it installs, and pick how
// long it lasts (including never). Everyone else keeps the old fixed-expiry codes.
const fs = require('fs');
const os = require('os');
const path = require('path');

process.env.DATA_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'lux-codes-test-'));

const { Harness } = require('./luxcloudHarness');

const h = new Harness();

const MOD_A = { projectId: 'AANobbMI', versionId: 'v1', fileName: 'sodium-1.jar', title: 'Sodium' };
const MOD_A2 = { projectId: 'AANobbMI', versionId: 'v2', fileName: 'sodium-2.jar', title: 'Sodium' };
const MOD_B = { projectId: 'P7dR8mSH', versionId: 'f1', fileName: 'fabric-api.jar', title: 'Fabric API' };

function exportBody(extra = {}) {
    return {
        name: 'Server Pack',
        mods: [MOD_A],
        resourcePacks: [],
        shaders: [],
        instanceVersion: '1.21.1',
        instanceLoader: 'fabric',
        keybinds: 'key_jump:key.keyboard.space',
        ownerUuid: 'mc-uuid-1',
        ...extra
    };
}

async function main() {
    await h.start({
        mount: (app) => require(path.join(__dirname, '..', 'codes_system.js'))(app, 'test-admin-password', h.pool)
    });
    await h.pool.query(`
        CREATE TABLE IF NOT EXISTS modpack_codes (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code VARCHAR(8) UNIQUE NOT NULL,
            owner_uuid VARCHAR(100),
            owner_ip VARCHAR(45),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    `);

    const adminId = await h.createUser({ googleId: 'g-admin', username: 'boss' });
    const userId = await h.createUser({ googleId: 'g-user', username: 'player' });
    await h.pool.query('UPDATE users SET role = ? WHERE id = ?', ['admin', adminId]);

    const adminToken = (await h.authorizeDevice({
        user: { id: adminId, username: 'boss', role: 'admin', banned: false },
        deviceUuid: 'dev-admin-0001'
    })).accessToken;
    const userToken = (await h.authorizeDevice({
        user: { id: userId, username: 'player', role: 'user', banned: false },
        deviceUuid: 'dev-user-0001'
    })).accessToken;

    let res;

    h.section('1) Normale Codes bleiben wie bisher');

    res = await h.request({ method: 'POST', url: '/api/modpack/save', body: exportBody() });
    h.check('Export ohne Konto -> 200', res.status === 200 && res.body.success, res.body);
    const plainCode = res.body.code;
    h.check('kein Live-Code', res.body.live === false && res.body.expiryMode === 'default', res.body);
    const sevenDays = 7 * 24 * 60 * 60 * 1000;
    h.check('laeuft nach 7 Tagen ab', Math.abs(res.body.expires - (Date.now() + sevenDays)) < 60000, res.body.expires);

    res = await h.request({ method: 'POST', url: '/api/modpack/save', body: exportBody({ live: true }) });
    h.check('Live ohne Konto -> 403', res.status === 403, res.body);

    res = await h.request({ method: 'POST', url: '/api/modpack/save', token: userToken, body: exportBody({ expiry: 'never' }) });
    h.check('"nie ablaufen" als normaler Nutzer -> 403', res.status === 403, res.body);

    res = await h.request({ url: '/api/modpack/admin/status', token: userToken });
    h.check('Nutzer ist kein Admin', res.status === 200 && res.body.isAdmin === false, res.body);

    res = await h.request({ method: 'PUT', url: `/api/modpack/${plainCode}/content`, token: userToken, body: { mods: [] } });
    h.check('Nutzer darf keinen Code aktualisieren -> 403', res.status === 403, res.body);

    res = await h.request({ method: 'PUT', url: `/api/modpack/${plainCode}/content`, body: { mods: [] } });
    h.check('ohne Anmeldung -> 401', res.status === 401, res.body);

    h.section('2) Admin erstellt einen Live-Code, der nie ablaeuft');

    res = await h.request({ url: '/api/modpack/admin/status', token: adminToken });
    h.check('Admin wird erkannt', res.status === 200 && res.body.isAdmin === true, res.body);

    res = await h.request({ method: 'POST', url: '/api/modpack/save', token: adminToken, body: exportBody({ live: true, expiry: 'never' }) });
    h.check('Live-Export -> 200', res.status === 200 && res.body.success, res.body);
    const liveCode = res.body.code;
    h.check('live, Revision 1, laeuft nie ab',
        res.body.live === true && res.body.revision === 1 && res.body.expiryMode === 'never' && res.body.expires === null, res.body);

    res = await h.request({ method: 'POST', url: '/api/modpack/save', token: adminToken, body: exportBody({ expiry: 9999 }) });
    h.check('ungueltige Laufzeit -> 400', res.status === 400, res.body);

    res = await h.request({ url: `/api/modpack/${liveCode}` });
    h.check('Import liefert live + Revision', res.status === 200 && res.body.data.live === true && res.body.data.revision === 1, res.body.data);
    h.check('Import zaehlt als Nutzung', res.body.data.uses === 1, res.body.data.uses);

    res = await h.request({ url: `/api/modpack/${liveCode}/live` });
    h.check('Live-Abfrage -> Revision 1', res.status === 200 && res.body.data.revision === 1, res.body);
    h.check('Live-Abfrage ohne Besitzerdaten und Einstellungen',
        !('owner_ip' in res.body.data) && !('keybinds' in res.body.data), Object.keys(res.body.data));

    h.section('3) Admin aktualisiert den Inhalt, der Code bleibt gleich');

    res = await h.request({
        method: 'PUT',
        url: `/api/modpack/${liveCode}/content`,
        token: adminToken,
        body: { mods: [MOD_A2, MOD_B], resourcePacks: [], shaders: [], instanceVersion: '1.21.1', instanceLoader: 'fabric' }
    });
    h.check('Update -> 200, Revision 2', res.status === 200 && res.body.code === liveCode && res.body.revision === 2, res.body);

    res = await h.request({ url: `/api/modpack/${liveCode}/live` });
    h.check('neue Mods kommen an',
        res.body.data.revision === 2 && res.body.data.mods.map((m) => m.fileName).join(',') === 'sodium-2.jar,fabric-api.jar', res.body.data.mods);

    res = await h.request({ url: `/api/modpack/${liveCode}/preview` });
    h.check('Vorschau zeigt den Live-Stand', res.status === 200 && res.body.data.live === true && res.body.data.mods.length === 2, res.body.data);

    res = await h.request({ method: 'PUT', url: `/api/modpack/${plainCode}/content`, token: adminToken, body: { mods: [] } });
    h.check('normaler Code laesst sich nicht live aktualisieren -> 409', res.status === 409, res.body);

    h.section('4) Laufzeit und Live-Modus nachtraeglich aendern');

    res = await h.request({ method: 'PATCH', url: `/api/modpack/${plainCode}/settings`, token: userToken, body: { expiry: 'never' } });
    h.check('Nutzer -> 403', res.status === 403, res.body);

    res = await h.request({ method: 'PATCH', url: `/api/modpack/${plainCode}/settings`, token: adminToken, body: { live: true, expiry: 30 } });
    h.check('Admin macht Code live mit 30 Tagen', res.status === 200 && res.body.live === true && res.body.expiryMode === 'custom', res.body);
    h.check('Ablauf in 30 Tagen', Math.abs(res.body.expires - (Date.now() + 30 * 24 * 60 * 60 * 1000)) < 60000, res.body.expires);

    res = await h.request({ url: '/api/modpack/my-codes?uuid=mc-uuid-1' });
    const listed = (res.body.codes || []).find((c) => c.code === liveCode);
    h.check('"Meine Codes" zeigt Live-Status', listed && listed.live === true && listed.revision === 2 && listed.expiryMode === 'never', listed);

    h.section('5) Abgelaufene Admin-Laufzeit');

    const file = path.join(process.env.DATA_DIR, 'codes', `${plainCode}.json`);
    const stored = JSON.parse(fs.readFileSync(file, 'utf8'));
    stored.expires = Date.now() - 1000;
    fs.writeFileSync(file, JSON.stringify(stored));

    res = await h.request({ url: `/api/modpack/${plainCode}` });
    h.check('abgelaufener Code -> 404', res.status === 404, res.body);
    res = await h.request({ url: `/api/modpack/${plainCode}/live` });
    h.check('Live-Abfrage eines abgelaufenen Codes -> 404', res.status === 404, res.body);
}

main()
    .catch((err) => {
        console.error(err);
        h.failed += 1;
    })
    .finally(() => {
        try { fs.rmSync(process.env.DATA_DIR, { recursive: true, force: true }); } catch { /* ignore */ }
        h.finish();
    });
